# Generated by Django 3.2.9 on 2021-12-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_character_characterrequiredstate_dataset_hierarchies_item_itemnames_itempicture_languages_state_taxo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=8)),
                ('std', models.BooleanField()),
                ('label', models.CharField(max_length=256)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.icon')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.extrafield')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.taxon')),
            ],
            options={
                'unique_together': {('taxon', 'field')},
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntryByLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.dictionaryentry')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.languages')),
            ],
            options={
                'unique_together': {('entry', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasc', models.CharField(max_length=256)),
                ('page', models.IntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.book')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.taxon')),
            ],
            options={
                'unique_together': {('taxon', 'book')},
            },
        ),
    ]
