# Generated by Django 3.2.9 on 2021-12-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_book_bookinfo_dictionaryentry_dictionaryentrybylang_extrafield_extrafieldvalue_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
