# Generated by Django 3.2.9 on 2021-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_dataset_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ref',
            field=models.CharField(default='a', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='ref',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('ref', 'dataset')},
        ),
    ]
