# Generated by Django 3.2.9 on 2021-12-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20211211_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hierarchies',
            new_name='Hierarchie',
        ),
        migrations.RenameModel(
            old_name='ItemNames',
            new_name='ItemName',
        ),
    ]
