# Generated by Django 3.2.9 on 2021-12-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_auto_20211211_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hierarchie',
            new_name='Hierarchy',
        ),
    ]
