# Generated by Django 3.2.9 on 2021-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_rename_hierarchie_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='taxon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
