# Generated by Django 3.2.9 on 2021-12-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20211211_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', to='hub.item'),
        ),
    ]
