# Generated by Django 3.2.9 on 2021-12-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_hierarchy_ancestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempicture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='hub.item'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='hub.item'),
        ),
    ]
