# Generated by Django 3.2.9 on 2021-12-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20211229_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryVersion',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='creation_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to='hub.dictionaryversion'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='deletion_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_entries', to='hub.dictionaryversion'),
        ),
    ]
