# Generated by Django 3.2.9 on 2022-01-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20211231_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
