# Generated by Django 3.2.9 on 2022-01-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_auto_20220101_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='hub.item'),
        ),
    ]
