# Generated by Django 4.1.1 on 2022-09-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_taxon_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentrybylang',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.dictionaryentry'),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'number')},
            },
        ),
    ]
