# Generated by Django 4.1.1 on 2022-09-24 13:29

from datetime import datetime
from django.db import migrations, models


def init_dataset_versions(apps, schema_editor):
    Dataset: models.Model = apps.get_model('hub', 'Dataset')
    DatasetVersion: models.Model = apps.get_model('hub', 'DatasetVersion')
    versions = []
    for dataset in Dataset.objects.all():
        versions.append(DatasetVersion(dataset=dataset, number=1, created_on=datetime.now()))
    DatasetVersion.objects.bulk_create(versions)

class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_alter_dictionaryentrybylang_entry_datasetversion'),
    ]

    operations = [
        migrations.RunPython(init_dataset_versions),
    ]
