# Generated by Django 4.1.1 on 2022-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_auto_20220924_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creation_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to='hub.datasetversion'),
        ),
        migrations.AddField(
            model_name='item',
            name='deletion_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', to='hub.datasetversion'),
        ),
    ]
