# Generated by Django 4.1.1 on 2022-09-24 13:52

from django.db import migrations, models


def init_item_creation_verions(apps, schema_editor):
    Dataset: models.Model = apps.get_model('hub', 'Dataset')
    DatasetVersion: models.Model = apps.get_model('hub', 'DatasetVersion')
    Item: models.Model = apps.get_model('hub', 'Item')
    for dataset in Dataset.objects.all():
        items = Item.objects.filter(dataset=dataset)
        version = DatasetVersion.objects.filter(dataset=dataset, number=1).first()
        for item in items:
            item.creation_version = version
        items.bulk_update(items, ['creation_version'])

class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_item_creation_version_item_deletion_version'),
    ]

    operations = [
        migrations.RunPython(init_item_creation_verions),
    ]
