# Generated by Django 4.1.4 on 2022-12-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_alter_item_unique_together_remove_item_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInherentState',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inherent_state', serialize=False, to='hub.character')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.state')),
            ],
        ),
    ]
