# Generated by Django 4.1.4 on 2022-12-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_characterinherentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinherentstate',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inherent_character', to='hub.state'),
        ),
    ]
